"""Regenerate bundled effects from the four original packs (Pillow required).

Normal build.py uses the checked-in output and does not require Pillow.
Only public names, categories and GIF bytes are copied; source prompts and
machine-specific paths in the original manifests are deliberately excluded.
"""
import base64
import hashlib
import io
import re
import json
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / 'assets'
OUT = ROOT / 'effect-assets'
PACKS = [
    ('reactions', 'gif_pack_40_v1', '表情與慶祝 · 40', 'Reactions & celebration · 40'),
    ('effects', 'gif_effects_50_v1', '常用效果 · 50', 'Everyday effects · 50'),
    ('shorts', 'gif_shorts_100_v1', '短影音效果 · 100', 'Short video effects · 100'),
    ('wild', 'gif_wild_50_v1', '誇張效果 · 50', 'Bold effects · 50'),
]
def repair_repeated_headers(raw):
    # Two original packs contain a repeated logical-screen header before their
    # final transparent frame. Pillow accepts it; Edge stops before that frame.
    # Remove ONLY an identical header at a parsed block boundary. Pixel data,
    # palette, frame delays and disposal bytes remain unchanged.
    header_size = 13 + (3 * (2 ** ((raw[10] & 7) + 1)) if raw[10] & 128 else 0)
    header = raw[:header_size]
    i = header_size
    repaired = 0
    while i < len(raw):
        if raw[i:i+6] in (b'GIF87a', b'GIF89a'):
            if raw[i:i+header_size] != header:
                raise ValueError('Unexpected different embedded GIF header')
            raw = raw[:i] + raw[i+header_size:]
            repaired += 1
            continue
        tag = raw[i]
        i += 1
        if tag == 0x3b:
            break
        if tag == 0x21:
            i += 1
        elif tag == 0x2c:
            packed = raw[i+8]
            i += 9
            if packed & 128:
                i += 3 * 2 ** ((packed & 7) + 1)
            i += 1  # LZW minimum code size
        else:
            raise ValueError(f'Invalid GIF block {tag} at {i-1}')
        while raw[i]:
            i += 1 + raw[i]
        i += 1
    return raw, repaired

OUT.mkdir(parents=True, exist_ok=True)
catalog = []
for pack, folder, label, english in PACKS:
    entries = json.loads((SOURCE / folder / 'manifest.json').read_text(encoding='utf-8-sig'))
    for entry in entries:
        key = f'{pack}-{int(entry["id"]):03}'
        source = SOURCE / folder / entry['gif']
        original = source.read_bytes()
        raw, repairs = repair_repeated_headers(original)
        if repairs:
            with Image.open(io.BytesIO(original)) as before, Image.open(io.BytesIO(raw)) as after:
                assert before.n_frames == after.n_frames
                for i in range(before.n_frames):
                    before.seek(i); after.seek(i)
                    assert before.info.get('duration') == after.info.get('duration')
                    assert before.convert('RGBA').tobytes() == after.convert('RGBA').tobytes()
            print(f'{key}: removed {repairs} repeated header; all pixels and timing unchanged')
        digest = hashlib.sha256(raw).hexdigest()
        # Content-addressed filenames avoid stale Pages/browser cache after updates.
        stem = key + '-' + digest[:12]
        with Image.open(io.BytesIO(raw)) as im:
            frames = im.n_frames
            duration = 0
            best, score = None, -1
            for i in range(frames):
                im.seek(i)
                duration += im.info.get('duration', 100)
                frame = im.convert('RGBA')
                # Prefer a visible representative frame over a blank first frame.
                alpha = frame.getchannel('A').resize((32, 32))
                current = sum(alpha.tobytes())
                if current > score:
                    best, score = frame.copy(), current
            best.thumbnail((144, 144), Image.Resampling.LANCZOS)
            best.save(OUT / (stem + '.webp'), 'WEBP', quality=82)
        payload = 'window.__nvEffectData(' + json.dumps(key) + ',' + json.dumps(base64.b64encode(raw).decode('ascii')) + ');\n'
        (OUT / (stem + '.js')).write_text(payload, encoding='ascii')
        catalog.append(dict(id=key, pack=pack, name=entry['name'],
                            en=entry['slug'].replace('_', ' ').capitalize(),
                            category=entry['category'], filename=source.name,
                            stem=stem, bytes=len(raw), sha256=digest, sourceSha256=hashlib.sha256(original).hexdigest(), headerRepairs=repairs,
                            frames=frames, duration=duration))
assert len(catalog) == 240 and len({e['id'] for e in catalog}) == 240
js = '// Generated by tools/build_effect_assets.py; public metadata only.\n'
js += 'const EFFECT_PACKS = ' + json.dumps([dict(id=p, name=n, en=e) for p, _, n, e in PACKS], ensure_ascii=False) + ';\n'
js += 'const EFFECT_CATALOG = ' + json.dumps(catalog, ensure_ascii=False, separators=(',', ':')) + ';\n'
(ROOT / 'src/26_effect_catalog.js').write_text(js, encoding='utf-8')
print(f'{len(catalog)} effects, {sum(e["bytes"] for e in catalog):,} original GIF bytes')

# Remove only obsolete generated files (content-hash names changed by repair).
keep = {e['stem'] + ext for e in catalog for ext in ('.js', '.webp')}
for path in OUT.iterdir():
    if re.fullmatch(r'(reactions|effects|shorts|wild)-[0-9]{3}-[0-9a-f]{12}\.(js|webp)', path.name) and path.name not in keep:
        path.unlink()
